### ISSUE TITLE
mysql extensions' .ini files are empty

### ISSUE THREAD

**Issue by Seldaek** [saz/puppet-php#3]
Given this config:

```
php::module { ['intl', 'gd', 'mysqlnd', 'mysql', 'curl']:
    notify => Class['php::fpm::service'],
}

php::module { ['apc']:
    notify => Class['php::fpm::service'],
    package_prefix => 'php-',
}

php::fpm::pool { "foo":
    user => "foo",
    group => "foo",
    listen => '127.0.0.1:9000',
}

php::conf { "nelmio":
    source => "puppet:///modules/nelmio/",
    notify => Class['php::fpm::service'],
}
```

I have a few issues:
- `cat /etc/php5/conf.d/mysql.ini` => empty
- `cat /etc/php5/fpm/conf.d/mysql.ini` => empty

Yet the `mysql.so` and `pdo.so` etc are present, they're just not loaded. On the other hand, `apc.ini` contains the proper `extension=apc.so` line. I don't see what is the difference between those two, they both seem to be treated equally by this module, yet only some are broken.

**Comment by lavoiesl** [comment]
I am having the same issue, with pdo as well

**Comment by saz** [comment]
You're missing php::conf for pdo.ini.

The file will be installed via your package manager, but due to the fact, that the /etc/php5/conf.d directory is fully managed (unmanaged files will be deleted), this file will be removed. If you add the php::conf part after the file is removed and you're not setting source or content parameter, Puppet will create an empty file.

If you add the php::conf part after the file is removed, you'll have to create the file manually.

**Comment by guilhermeblanco** [comment]
With latest commits and PRs that were merged, this issue is now fixed. =)

**Comment by saz** [comment]
Then I'll close this issue. If there are still problems, please open a new issue.

**Comment by woss** [comment]
they are still empty
